
fda_drug$gvkey<- NA
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ABBOTT", "1078", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ABBOTT LABS", "1078", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ABBVIE", "16101", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ABLE", "23000", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ABRAXIS", "178855", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ACACIA", "61940", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ACADIA", "141846", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ACELRX PHARMS", "185908", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ACERUS", "187672", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ACORDA", "156617", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ADAMAS PHARMA", "20042", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ADHERA", "29218", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AEGERION", "177313", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AERIE", "18749", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AGIOS", "18159", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AGOURON", "13308", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AHARMA", "1034", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AKCEA THERAPS", "32046", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AKORN", "14304", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ALCON", "1248", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ALEXION PHARM", "62263", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ALEXZA PHARMS", "166414", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ALKERMES", "24302", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ALLERGAN", "1284", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ALLIANCE PHARM", "11793", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ALNYLAM PHARMS", "264265", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AMAG PHARMS", "12250", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AMARIN", "28027", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AMGEN", "1602", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AMICUS THERAPS US", "175008", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AMNEAL", "18888", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AMPHASTAR PHARMS", "20659", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "APP PHARMS", "145512", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "APTALIS PHARMA US", "19424", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AQUESTIVE THERAP", "33743", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ARDELYX", "20645", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ARIAD", "30674", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ARMSTRONG PHARMS", "20899", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ARDELYX", "20645", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ARRAY BIOPHARMA", "141197", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ASSERTIO", "65944", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ASTRAZENECA", "28272", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ATHENA NEUROSCIENCES", "24661", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ATHENEX", "31405", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ATLAS PHARMS", "33214", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AUXILIUM PHARMS", "160272", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AVANIR PHARMS", "21776", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AVEDRO", "34682", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AVID RADIOPHARMS", "14603", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AVION", "28272", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AXCAN SCANDIPHARM", "61781", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "AYTU BIOSCIENCE", "179461", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BARR", "13365", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BAUSCH", "2085", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BAXTER HLTHCARE", "2086", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BAYER", "101076", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BEIGENE", "26376", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BIOCRYST", "29837", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BIOENVISION", "118733", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BIOFRONTERA", "282363", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BIOHAVEN PHARM", "31094", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BIOMARIN", "122257", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BLUEPRINT MEDICINES", "23407", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BRAEBURN PHARMA", "29696", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BRISTOL", "2403", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BRISTOLMYERS SQUIBB", "2403", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "BRISTOL MYERS SQUIBB", "2403", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CADENCE HEALTH", "175483", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CARACO", "30185", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CASI PHARMS", "63030", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CATALENT", "20228", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CATALYST PHARMS", "175966", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CELATOR PHARMS", "18613", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CELGENE", "13599", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CENTOCOR", "2846", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CEPHALON", "23945", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CHATTEM", "2950", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CHIRON", "3011", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CIPHER PHARMS", "260838", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CITIUS PHARMS", "21807", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CLARUS", "185946", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CLOVIS ONCOLOGY", "196055", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "COHERUS BIOSCIENCES", "21841", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "COLLAGENEX", "23555", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "COPLEY PHARM", "25813", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CORCEPT THERAP", "146616", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CORNERSTONE", "181617", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CUMBERLAND PHARMS", "178097", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CYPRESS PHARM", "5841", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "CYTOGEN", "12274", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "DERMIRA", "21617", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "DOUGLAS PHARMS", "4057S", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "DURAMED", "12580", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "DURAMED RES", "12580", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "DURAMED PHARMS BARR", "12580", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "DUSA", "24898", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "DYAX", "112754", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "EAGLE PHARMS", "19784", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "EGALET", "18982", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "EISAI", "100418", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ELAN PHARM", "4245", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ELITE LABS", "106261", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "EMERALD INTL", "21687", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "EMERGENT", "176022", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "EMMAUS MEDCL", "23555", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ENDO PHARMS", "63645", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ENDO VENTURES", "63645", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "EPIZYME", "17808", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ESPERION THERAPS", "18162", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ESSENTIAL ISOTOPES", "62860", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ETON PHARMS", "33997", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "EVOLUS", "32919", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "EXELIXIS", "133885", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "EYEPOINT PHARMS", "253527", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "FLEXION THERAPS", "19511", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "FOAMIX", "21522", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "FOREST LABS", "4843", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "FOREST PHARMS", "4843", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "GENENTECH", "5020", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "GENZYME", "12233", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "GILEAD", "24856", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "GILEAD SCIENCES", "24856", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "GLAXOSMITHKLINE", "5180", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "GLOBAL BLOOD THERAPS", "25349", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "GUARDIAN DRUG", "5364", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HALOZYME THERAP", "151630", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HERON THERAPS", "13786", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HI TECH", "25623", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HI TECH PHARMA", "25623", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HI TECH PHARMA CO", "25623", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HITECH PHARMA", "25623", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HITECH PHARMA CO", "25623", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HITECH PHARMACAL", "25623", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HORIZON", "185355", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HORIZON PHARMA", "185355", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HORIZON PHARMA USA", "185355", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HORIZON THERAP", "185355", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HORIZON THERAPEUTICS IRELAND", "185355", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HOSPIRA", "160255", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HOSPIRA WORLDWIDE", "160255", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HUMAN GENOME SCIENCES", "29312", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "IMCLONE", "24699", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "IMMUNEX", "5885", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "IMPAX LABS", "61745", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "INSMED", "136186", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "INSYS THERAP", "179731", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "INTELLIPHARMACEUTICS", "183739", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "INTERCEPT PHARMS", "14320", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "INTERPHARM", "6129", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "IVAX PHARMS", "14446", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "IVAX RES", "14446", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "IVAX SUB TEVA PHARMS", "14446", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "IVC INDS", "29826", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "JAVELIN PHARMS", "143892", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "JAZZ PHARMS", "177287", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "JOHNSON AND JOHNSON", "6266", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "KADMON PHARMS", "27476", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "KALA PHARMS", "32018", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "KALAPHARM", "32018", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "KARYOPHARM THERAPS", "18930", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "KERYX BIOPHARMS", "138126", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "KEY PHARMS", "6414", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "KING PHARMS", "112033", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "KING PFIZER", "8530", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "KNIGHT THERAPS", "19901", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "KYTHERA BIOPHARMS", "5241", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "L PERRIGO CO", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "LANTHEUS MEDCL", "186497", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "LEINER", "124555", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "LEXICON PHARMS", "133868", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "LILLY", "6730", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "LOTUS PHARM CO", "163088", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "LYPHOMED", "6854", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MARSAM PHARMS", "13283", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MAST MM", "63790", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MATRIX LABS", "24877", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MATRIX MEDCL", "24877", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MCGAW", "27964", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MEDICIS ", "21186", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MEDICIS PHARMS", "21186", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MEDICURE", "119297", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MEDIMMUNE", "24008", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MEDIMMUNE ONCOLOGY", "24008", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MELINTA THERAP", "196856", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MELINTA", "196856", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MERCK", "7257", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MERCK KGAA", "7257", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MERIDIAN MEDCL", "7257", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MGI PHARMA", "7504", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MICROBIX BIOSYSTEMS", "127514", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MIDATECH PHARMA US", "318815", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MILES", "7392", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MILLENNIUM PHARMS", "7257", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MYLAN", "7637", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MYLAN BERTEK", "7637", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "MYLAN TEORANTA", "7637", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NABRIVA", "26148", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NEOS THERAP", "25377", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NEOS THERAPS", "25377", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NEUROCRINE", "62921", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NEW RIVER", "160374", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NOVA LABS", "8012", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NOVARTIS", "101310", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NOVEN", "7257", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NOVEN PHARMS", "7257", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NOVEN THERAP", "14918", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NOVO", "8020", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NPS PHARMS", "30255", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NUVO PHARMS", "106179", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NUVO PHARM", "106179", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "NYCOMED US", "101397", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "OCULAR THERAPEUTIX", "21015", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "OMEROS", "183593", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ONYX THERAP", "62826", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "OPTINOSE US", "32451", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ORAPHARMA", "132641", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "OSI PHARMS", "12180", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "OSMOTICA", "34160", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "OSMOTICA PHARMS", "34160", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "OSMOTICA PHARM US", "34160", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "OTONOMY", "21145", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "OUTLOOK PHARMS", "26817", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PACIFIC PHARMA", "12712", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PACIRA PHARMS", "185836", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PANACEA BIOTEC", "185261", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PAR PHARM", "8333", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PARATEK PHARMS", "15539", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PARKE DAVIS", "8352", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PARKEDAVIS", "8352", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PARNELL", "20654", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO CO", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO CO TENNESSEE", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO ISRAEL", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO NEW YORK", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO PHARMA INTL", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO PHARMS CO", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO R AND D", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO UK FO", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO UK FO PARTNERSHIP", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PERRIGO R AND D", "24782", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PFIZER", "8530", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PFIZER GLOBAL", "8530", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PFIZER LABS", "8530", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PHARMACIA", "7536", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PHARMACIA AND UPJOHN", "11040", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PHARMACYCLICS", "61448", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PHARMAXIS", "259073", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PHARMOS", "12757", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PLX PHARMS", "26336", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PORTOLA PHARMS", "17931", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PRECISION DERMAT", "34883", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PRECISION DOSE", "34883", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PRECISION NUCLEAR", "34883", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PRIMUS PHARMS", "186471", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PROGENICS PHARMS", "65872", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "PUMA BIOTECH", "170945", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "QUESTCOR PHARMA", "25906", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "RADIUS HEALTH", "170520", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "RADIUS PHARMS", "170520", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "RECRO GAINESVILLE", "19025", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "REDHILL", "296885", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "REGENERON PHARMACEUTICALS", "23812", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "RELIANT PHARMS", "164001", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "RELIANT HOLDINGS", "164001", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "RELYPSA", "18976", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "REXALL", "28469", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "RIGEL PHARMS", "133468", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ROBERTS OXYGEN CO", "20192", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ROBINS AH", "9183", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ROCHE", "25648", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ROCKWELL MEDCL", "66366", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ROCKWELL MEDICAL", "66366", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ROYCE LABS", "12369", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SAGE PRODS", "20943", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SAGE THERAP", "20943", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SAGENT PHARMS", "186045", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SALIX", "62977", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SANOFI", "101204", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SANTARUS", "157954", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SAREPTA THERAPS", "64857", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SCHERER LABS", "25648", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SCHERER RP", "9458", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SCHERING PLOUGH", "9459", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SEATTLE GENETICS", "141460", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SERONO", "102045", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SHIRE", "212340", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SHIRE RICHWOOD", "212340", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SICOR BIOTECH", "22250", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SICOR PHARMS", "22250", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SIGA TECHNOLOGIES", "65376", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SKINMEDICA", "163979", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SKYEPHARMA AG", "112408", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SMITH KLINE & FRENCH", "9775", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "SMITHKLINE BEECHAM", "9775", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "STEMLINE THERAPEUTICS", "171022", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "STERLING WINTHROP", "10066", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "STERLING", "10066", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "STRONGBRIDGE US", "293919", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TARO PHARM INDS", "30554", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TARO PHARMA USA", "30554", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TARO PHARMS", "30554", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TARO PHARMS IRELAND", "30554", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TARO PHARMS NORTH", "30554", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TELIGENT", "5888", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TELIGENT PHARMA", "5888", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TEVA", "14538", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TEVA PHARM", "14538", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TEVA RESPIRATORY", "14538", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "THERATECHNOLOGIES", "29476", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "THERAVANCE", "20233", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "TITAN PHARMS", "61836", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ULTRAGENYX PHARMS", "19149", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "ULURU", "25882", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "UNITED THERAP", "121440", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "UROGEN PHARMA", "31061", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "VALEANT", "9340", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "VALEANT BERMUDA", "9340", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "VALEANT PHARMS INTL", "9340", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "VANDA PHARMS", "166435", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "VERASTEM", "194255", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "VERTEX PHARMS", "24344", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "VICURON", "138404", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "VIVUS", "30007", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "WARNER CHILCOTT", "175163", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "WYETH", "1478", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "WYETH CONS", "1478", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "XANODYNE PHARM", "179833", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "XANODYNE PHARMS", "179833", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "XERIS", "33660", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "HOFFMANN LA ROCHE", "25648", fda_drug$gvkey)
fda_drug$gvkey <- ifelse(fda_drug$SponsorName == "JANSSEN BIOTECH", "2846", fda_drug$gvkey)



